"""empty message

Revision ID: bd832d1a59e3
Revises: ae09776f464e
Create Date: 2021-06-23 12:49:48.099695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd832d1a59e3'
down_revision = 'ae09776f464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('ticker', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'ticker')
    # ### end Alembic commands ###
