"""empty message

Revision ID: ae09776f464e
Revises: 93b1f099031e
Create Date: 2021-06-23 11:03:25.615552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae09776f464e'
down_revision = '93b1f099031e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('planetName', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'planetName')
    # ### end Alembic commands ###
