"""empty message

Revision ID: be91eec9408c
Revises: 6eb906f72a05
Create Date: 2021-06-23 15:48:02.537303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be91eec9408c'
down_revision = '6eb906f72a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ticker', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'ticker')
    # ### end Alembic commands ###
