"""empty message

Revision ID: 6eb906f72a05
Revises: bd832d1a59e3
Create Date: 2021-06-23 14:06:25.955633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb906f72a05'
down_revision = 'bd832d1a59e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('orderType', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'orderType')
    # ### end Alembic commands ###
