"""empty message

Revision ID: 0b8bcb01f0b9
Revises: be91eec9408c
Create Date: 2021-06-25 23:04:47.948390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8bcb01f0b9'
down_revision = 'be91eec9408c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('crypto', sa.String(length=50), nullable=False))
    op.add_column('planets', sa.Column('crypto', sa.String(length=50), nullable=False))
    op.add_column('planets', sa.Column('planet_leader', sa.String(length=50), nullable=False))
    op.add_column('planets', sa.Column('top_export', sa.String(length=50), nullable=False))
    op.alter_column('users', 'cash_balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('users', 'cash_balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('planets', 'top_export')
    op.drop_column('planets', 'planet_leader')
    op.drop_column('planets', 'crypto')
    op.drop_column('assets', 'crypto')
    # ### end Alembic commands ###
